run:
  go: "1.23"
  timeout: 5m
  tests: true
  modules-download-mode: readonly

issues:
  exclude-dirs-use-default: true

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - revive
    - stylecheck
    - gosimple
    - misspell
    - whitespace
    - ineffassign
    - typecheck
    - errcheck
    - govet
    - staticcheck
    - unused
    - unconvert
    - nosprintfhostport
    - gofumpt
    - sloglint
    - unparam
    - usestdlibvars
    - usetesting
    - gocritic
    - asciicheck
    - bidichk
    - gocheckcompilerdirectives
    - asasalint
    - durationcheck
    - exptostd
    - forbidigo
    - mirror
    - errorlint
    - errchkjson
    - errname
    - gosec
    - sqlclosecheck
    - rowserrcheck
    - noctx
    - bodyclose
    - prealloc
    - perfsprint
    - unconvert
    - gocyclo
    - testifylint
    - thelper
    - testpackage
    - tparallel
    - goheader
    - gomoddirectives
    - gomodguard
    - musttag
    - tagalign
    - iface
    - importas
    - loggercheck
    - canonicalheader
    - containedctx
    - copyloopvar
    - intrange
    - makezero
    - nolintlint
    - predeclared
    - wastedassign
    - ginkgolinter
    - goprintffuncname
    - inamedparam
    - promlinter
    - protogetter
    - reassign
