#!/usr/bin/env bash
#
# Zero-downtime production deployment via Docker + Nginx upstream switching.
#
# How it works:
#   1. Build new Docker image (frontend + swagger + enterprise Go binary)
#   2. Start canary container on alternate port (3000 ↔ 3001)
#   3. Health check + smoke test the canary
#   4. Switch Nginx upstream to canary (nginx reload — zero-downtime)
#   5. Gracefully drain old container (SIGTERM → 600s wait for in-flight requests)
#
# Usage:
#   ADMIN_KEY=xxx bash scripts/zero-downtime-deploy.sh                # Full deploy
#   ADMIN_KEY=xxx bash scripts/zero-downtime-deploy.sh --no-pull      # Skip git pull
#   bash scripts/zero-downtime-deploy.sh --build-only                 # Build image only
#   ADMIN_KEY=xxx bash scripts/zero-downtime-deploy.sh --rollback     # Emergency rollback
#
# Prerequisites:
#   - Docker + Docker Compose V2
#   - Nginx with deploy/nginx/aiproxy-upstream.conf installed
#   - ADMIN_KEY env var (for smoke tests)
#
# State file: /data/aiproxy/.active-port (tracks which port is currently serving)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "${ROOT_DIR}"

# ── Configuration ─────────────────────────────────────────────
STATE_FILE="/data/aiproxy/.active-port"
UPSTREAM_CONF="/etc/nginx/conf.d/aiproxy-upstream.conf"
LOCK_FILE="/tmp/aiproxy-deploy.lock"
DRAIN_TIMEOUT=600
HEALTH_TIMEOUT=90
STABILIZE_WAIT=10

COMPOSE_CMD="docker compose -f docker-compose.yaml -f docker-compose.prod.yaml"

# Determine the Docker Compose network name.
# Compose names it "<project>_default" where project = directory basename.
COMPOSE_PROJECT="$(basename "${ROOT_DIR}")"
COMPOSE_NETWORK="${COMPOSE_PROJECT}_default"

# ── Flags ─────────────────────────────────────────────────────
BUILD_ONLY=0
NO_PULL=0
ROLLBACK=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --build-only)   BUILD_ONLY=1;   shift ;;
    --no-pull)      NO_PULL=1;      shift ;;
    --rollback)     ROLLBACK=1;     shift ;;
    -h|--help)
      head -20 "$0" | tail -18
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

# ── Helpers ───────────────────────────────────────────────────
pass() { printf "\033[32m✓\033[0m %s\n" "$*"; }
fail() { printf "\033[31m✗\033[0m %s\n" "$*"; exit 1; }
info() { printf "\033[36m→\033[0m %s\n" "$*"; }
warn() { printf "\033[33m!\033[0m %s\n" "$*"; }

get_active_port() {
  if [[ -f "${STATE_FILE}" ]]; then
    cat "${STATE_FILE}"
  else
    echo "3000"
  fi
}

get_canary_port() {
  local active="$1"
  if [[ "${active}" == "3000" ]]; then
    echo "3001"
  else
    echo "3000"
  fi
}

# Find the running container on a given host port.
find_container_on_port() {
  local port="$1"
  # Use docker ps with port filter. The format "0.0.0.0:PORT->3000/tcp" matches.
  docker ps --format '{{.Names}}\t{{.Ports}}' 2>/dev/null \
    | grep -E "0\.0\.0\.0:${port}->" \
    | head -1 \
    | cut -f1
}

write_upstream() {
  local port="$1"
  sudo tee "${UPSTREAM_CONF}" > /dev/null <<EOF
# Auto-generated by zero-downtime-deploy.sh — do not edit manually.
# Active port: ${port}
# Updated: $(date -Iseconds)

upstream aiproxy_backend {
    server 127.0.0.1:${port};
}
EOF
}

# Extract environment variables from compose config into a docker env-file.
# Returns the path to a temporary file suitable for `docker run --env-file`.
build_env_file() {
  local env_file
  env_file=$(mktemp /tmp/aiproxy-deploy-env.XXXXXX)
  ${COMPOSE_CMD} config --format json 2>/dev/null \
    | python3 -c "
import sys, json
cfg = json.load(sys.stdin)
svc = cfg.get('services', {}).get('aiproxy', {})
for k, v in svc.get('environment', {}).items():
    if v is not None:
        print(f'{k}={v}')
" > "${env_file}" 2>/dev/null || true
  echo "${env_file}"
}

# ── Cleanup trap ──────────────────────────────────────────────
CANARY_STARTED=0
TRAFFIC_SWITCHED=0
OLD_PORT=""
CANARY_PORT=""

cleanup_on_failure() {
  local exit_code=$?
  if [[ ${exit_code} -eq 0 ]]; then
    return
  fi

  warn "Deploy failed (exit ${exit_code}). Cleaning up..."

  if [[ ${TRAFFIC_SWITCHED} -eq 1 && -n "${OLD_PORT}" ]]; then
    warn "Traffic was already switched. Reverting Nginx to port ${OLD_PORT}..."
    write_upstream "${OLD_PORT}"
    if sudo nginx -t >/dev/null 2>&1; then
      sudo nginx -s reload
      pass "Nginx reverted to port ${OLD_PORT}"
    else
      # Do NOT call fail() here — it would exit and re-trigger this trap.
      printf "\033[31m✗\033[0m CRITICAL: Nginx config invalid after revert — manual intervention required!\n" >&2
    fi
  fi

  if [[ ${CANARY_STARTED} -eq 1 ]]; then
    warn "Stopping canary container..."
    docker stop --time=10 aiproxy-canary 2>/dev/null || true
    docker rm -f aiproxy-canary 2>/dev/null || true
    pass "Canary container removed"
  fi

  # Clean up temp env file
  rm -f /tmp/aiproxy-deploy-env.* 2>/dev/null || true

  warn "Old service is still running — no traffic impact."
}

trap cleanup_on_failure EXIT

# ── Pre-flight checks ────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  fail "docker not found"
fi
if ! docker compose version >/dev/null 2>&1; then
  fail "docker compose V2 not found"
fi
if ! command -v nginx >/dev/null 2>&1 && ! sudo command -v nginx >/dev/null 2>&1; then
  fail "nginx not found"
fi

echo ""
info "=========================================="
info "AI Proxy Zero-Downtime Deployment"
info "=========================================="
echo ""

DEPLOY_START=$(date +%s)

# ── Acquire deploy lock ───────────────────────────────────────
exec 200>"${LOCK_FILE}"
if ! flock -n 200; then
  fail "Another deploy is in progress (lock: ${LOCK_FILE})"
fi

# ── Read current state ────────────────────────────────────────
ACTIVE_PORT=$(get_active_port)
CANARY_PORT=$(get_canary_port "${ACTIVE_PORT}")
OLD_PORT="${ACTIVE_PORT}"

info "Active port: ${ACTIVE_PORT}"
info "Canary port: ${CANARY_PORT}"

# ══════════════════════════════════════════════════════════════
# ROLLBACK MODE
# ══════════════════════════════════════════════════════════════
if [[ "${ROLLBACK}" == "1" ]]; then
  info "=== Emergency Rollback ==="

  if ! docker image inspect aiproxy:rollback >/dev/null 2>&1; then
    fail "No rollback image found (aiproxy:rollback). Cannot rollback."
  fi

  info "Starting rollback container on port ${CANARY_PORT}..."
  ENV_FILE=$(build_env_file)

  docker run -d \
    --name aiproxy-canary \
    --network "${COMPOSE_NETWORK}" \
    --restart unless-stopped \
    -p "${CANARY_PORT}:3000" \
    --env-file "${ENV_FILE}" \
    aiproxy:rollback

  rm -f "${ENV_FILE}"

  CANARY_STARTED=1

  info "Waiting for rollback container health check..."
  ELAPSED=0
  while [[ ${ELAPSED} -lt ${HEALTH_TIMEOUT} ]]; do
    if curl -sf "http://localhost:${CANARY_PORT}/api/status" >/dev/null 2>&1; then
      pass "Rollback container healthy"
      break
    fi
    sleep 2
    ELAPSED=$((ELAPSED + 2))
  done

  if [[ ${ELAPSED} -ge ${HEALTH_TIMEOUT} ]]; then
    fail "Rollback container health check timeout"
  fi

  # Switch traffic
  write_upstream "${CANARY_PORT}"
  sudo nginx -t || fail "Nginx config invalid"
  sudo nginx -s reload
  TRAFFIC_SWITCHED=1
  pass "Nginx switched to rollback container (port ${CANARY_PORT})"

  # Drain old
  OLD_CONTAINER=$(find_container_on_port "${ACTIVE_PORT}")
  if [[ -n "${OLD_CONTAINER}" ]]; then
    info "Draining old container: ${OLD_CONTAINER}..."
    docker stop --time="${DRAIN_TIMEOUT}" "${OLD_CONTAINER}" 2>/dev/null || true
    docker rm -f "${OLD_CONTAINER}" 2>/dev/null || true
    pass "Old container removed"
  fi

  # Finalize
  echo "${CANARY_PORT}" | sudo tee "${STATE_FILE}" > /dev/null
  docker rename aiproxy-canary "aiproxy-active" 2>/dev/null || true

  CANARY_STARTED=0
  TRAFFIC_SWITCHED=0

  pass "Rollback complete. Active port: ${CANARY_PORT}"
  exit 0
fi

# ══════════════════════════════════════════════════════════════
# PHASE 0: Pre-flight
# ══════════════════════════════════════════════════════════════
info "Phase 0/5: Pre-flight checks..."

# Ensure infra is running
${COMPOSE_CMD} up -d pgsql redis 2>/dev/null
sleep 2

# Verify compose network exists
if ! docker network inspect "${COMPOSE_NETWORK}" >/dev/null 2>&1; then
  fail "Docker network '${COMPOSE_NETWORK}' not found. Run 'docker compose up -d pgsql redis' first."
fi

# Clean up any leftover canary from a previous failed deploy
if docker ps -a --format '{{.Names}}' | grep -q '^aiproxy-canary$'; then
  warn "Removing leftover canary container from previous deploy..."
  docker rm -f aiproxy-canary 2>/dev/null || true
fi

pass "Pre-flight checks passed"

# ══════════════════════════════════════════════════════════════
# PHASE 1: Build
# ══════════════════════════════════════════════════════════════

# Step 1a: Pull code
if [[ "${NO_PULL}" == "0" ]]; then
  info "Phase 1/5: Pulling latest code..."

  CURRENT_BRANCH=$(git branch --show-current)
  info "Branch: ${CURRENT_BRANCH}"

  if ! git diff --quiet || ! git diff --cached --quiet; then
    warn "Uncommitted changes detected — stashing..."
    git stash push -m "deploy-auto-stash-$(date +%Y%m%d-%H%M%S)"
    STASHED=1
  else
    STASHED=0
  fi

  git pull --rebase origin "${CURRENT_BRANCH}"
  pass "Code updated"

  if [[ "${STASHED}" == "1" ]]; then
    warn "Restoring stashed changes..."
    git stash pop || warn "Stash pop failed — resolve manually after deploy"
  fi
else
  info "Phase 1/5: Skipping pull (--no-pull)"
fi

# Step 1b: Tag current image for rollback
if docker image inspect aiproxy:local >/dev/null 2>&1; then
  docker tag aiproxy:local aiproxy:rollback
  pass "Current image tagged as aiproxy:rollback"
else
  warn "No existing aiproxy:local image — skip rollback tag"
fi

# Step 1c: Build new image
info "Building Docker image..."
${COMPOSE_CMD} build --no-cache aiproxy
pass "Docker image built: aiproxy:local"

# Step 1d: Verify image
info "Verifying image contents..."
VERIFY_OUTPUT=$(docker run --rm --entrypoint sh aiproxy:local -c \
  'strings /usr/local/bin/aiproxy | grep -c "enterprise" || echo 0' 2>/dev/null)
if [[ "${VERIFY_OUTPUT}" -gt 0 ]]; then
  pass "Enterprise module verified (${VERIFY_OUTPUT} symbols)"
else
  fail "Enterprise module NOT found in image"
fi

FRONTEND_CHECK=$(docker run --rm --entrypoint sh aiproxy:local -c \
  'strings /usr/local/bin/aiproxy | grep -c "</html>" || echo 0' 2>/dev/null)
if [[ "${FRONTEND_CHECK}" -gt 0 ]]; then
  pass "Frontend embedded in image"
else
  fail "Frontend NOT embedded in image"
fi

if [[ "${BUILD_ONLY}" == "1" ]]; then
  echo ""
  pass "Build complete (--build-only). Image: aiproxy:local"
  # Reset trap — clean exit
  CANARY_STARTED=0
  TRAFFIC_SWITCHED=0
  exit 0
fi

# ══════════════════════════════════════════════════════════════
# PHASE 2: Start Canary
# ══════════════════════════════════════════════════════════════
info "Phase 2/5: Starting canary on port ${CANARY_PORT}..."

ENV_FILE=$(build_env_file)

docker run -d \
  --name aiproxy-canary \
  --network "${COMPOSE_NETWORK}" \
  --restart unless-stopped \
  -p "${CANARY_PORT}:3000" \
  --env-file "${ENV_FILE}" \
  aiproxy:local

rm -f "${ENV_FILE}"

CANARY_STARTED=1
pass "Canary container started"

# Health check loop
info "Waiting for canary health check (timeout: ${HEALTH_TIMEOUT}s)..."
ELAPSED=0
while [[ ${ELAPSED} -lt ${HEALTH_TIMEOUT} ]]; do
  HTTP_CODE=$(curl -sf -o /dev/null -w "%{http_code}" "http://localhost:${CANARY_PORT}/api/status" 2>/dev/null || echo "000")
  if [[ "${HTTP_CODE}" == "200" ]]; then
    pass "Canary health check passed"
    break
  fi
  sleep 2
  ELAPSED=$((ELAPSED + 2))
done

if [[ ${ELAPSED} -ge ${HEALTH_TIMEOUT} ]]; then
  fail "Canary health check timeout (${HEALTH_TIMEOUT}s)"
fi

# Verify enterprise build
ENTERPRISE_CHECK=$(curl -sf "http://localhost:${CANARY_PORT}/api/status" 2>/dev/null \
  | python3 -c "import sys,json; d=json.load(sys.stdin); print('true' if d.get('data',{}).get('isEnterprise') else 'false')" 2>/dev/null || echo "false")
if [[ "${ENTERPRISE_CHECK}" != "true" ]]; then
  fail "Canary is NOT enterprise build — isEnterprise=false"
fi
pass "Enterprise build confirmed"

# Run smoke tests if ADMIN_KEY is available
ADMIN_KEY="${ADMIN_KEY:-}"
if [[ -n "${ADMIN_KEY}" ]]; then
  info "Running smoke tests against canary..."
  if ADMIN_KEY="${ADMIN_KEY}" API_KEY="${API_KEY:-}" \
    bash scripts/smoke-test.sh "http://localhost:${CANARY_PORT}"; then
    pass "Canary smoke tests passed"
  else
    fail "Canary smoke tests failed — aborting deploy"
  fi
else
  warn "ADMIN_KEY not set — skipping smoke tests (strongly recommended)"
fi

# ══════════════════════════════════════════════════════════════
# PHASE 3: Switch Traffic
# ══════════════════════════════════════════════════════════════
info "Phase 3/5: Switching Nginx upstream to port ${CANARY_PORT}..."

# Backup current upstream config
if [[ -f "${UPSTREAM_CONF}" ]]; then
  sudo cp "${UPSTREAM_CONF}" "${UPSTREAM_CONF}.bak"
fi

write_upstream "${CANARY_PORT}"

if ! sudo nginx -t >/dev/null 2>&1; then
  warn "Nginx config test failed — reverting..."
  if [[ -f "${UPSTREAM_CONF}.bak" ]]; then
    sudo cp "${UPSTREAM_CONF}.bak" "${UPSTREAM_CONF}"
  fi
  fail "Nginx config invalid after upstream switch"
fi

sudo nginx -s reload
TRAFFIC_SWITCHED=1
pass "Nginx reloaded — traffic now on port ${CANARY_PORT}"

# Stabilization wait
info "Waiting ${STABILIZE_WAIT}s for stabilization..."
sleep "${STABILIZE_WAIT}"

# Quick verification through Nginx
HTTP_CHECK=$(curl -sf -o /dev/null -w "%{http_code}" "http://localhost:80/api/status" 2>/dev/null || echo "000")
if [[ "${HTTP_CHECK}" == "200" ]]; then
  pass "Production endpoint verified via Nginx"
else
  warn "Production endpoint returned HTTP ${HTTP_CHECK} — check manually"
fi

# ══════════════════════════════════════════════════════════════
# PHASE 4: Drain Old Container
# ══════════════════════════════════════════════════════════════
info "Phase 4/5: Draining old container (timeout: ${DRAIN_TIMEOUT}s)..."

OLD_CONTAINER=$(find_container_on_port "${ACTIVE_PORT}")
if [[ -n "${OLD_CONTAINER}" ]]; then
  info "Old container: ${OLD_CONTAINER}"
  docker stop --time="${DRAIN_TIMEOUT}" "${OLD_CONTAINER}"
  docker rm "${OLD_CONTAINER}" 2>/dev/null || true
  pass "Old container drained and removed"
else
  warn "No container found on port ${ACTIVE_PORT} — skipping drain"
fi

# ══════════════════════════════════════════════════════════════
# PHASE 5: Finalize
# ══════════════════════════════════════════════════════════════
info "Phase 5/5: Finalizing..."

# Update state file
echo "${CANARY_PORT}" | sudo tee "${STATE_FILE}" > /dev/null
pass "State file updated: active port = ${CANARY_PORT}"

# Rename canary to active
docker rename aiproxy-canary "aiproxy-active" 2>/dev/null || true
pass "Container renamed to aiproxy-active"

# Clean up backup
sudo rm -f "${UPSTREAM_CONF}.bak"

# Reset trap state — successful deploy
CANARY_STARTED=0
TRAFFIC_SWITCHED=0

# ── Summary ───────────────────────────────────────────────────
DEPLOY_END=$(date +%s)
DEPLOY_DURATION=$((DEPLOY_END - DEPLOY_START))

echo ""
info "=========================================="
pass "Zero-downtime deployment complete (${DEPLOY_DURATION}s)"
info "=========================================="
info "Active port: ${CANARY_PORT}"
info "Rollback:    bash scripts/zero-downtime-deploy.sh --rollback"
info "Logs:        docker logs -f aiproxy-active"
info "Status:      curl http://localhost:${CANARY_PORT}/api/status"
echo ""
