name: CI

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
    paths-ignore:
      - "**/*.md"
      - "**/*.yaml"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "**/*.md"
      - "**/*.yaml"

jobs:
  golangci-lint-aiproxy:
    name: Lint AI Proxy
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "core/go.mod"

      - name: Go test
        working-directory: core
        run: |
          go test -v -timeout 30s -count=1 ./...

      - name: Run Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          working-directory: core
          args: "--out-format colored-line-number --max-issues-per-linter 0 --max-same-issues 0 --config ./.golangci.yml"

      - name: Run Fix Linter
        uses: golangci/golangci-lint-action@v6
        if: ${{ failure() }}
        with:
          install-mode: none
          working-directory: core
          args: "--fix --out-format colored-line-number --max-issues-per-linter 0 --max-same-issues 0 --config ./.golangci.yml"

      - name: Auto Fix Diff Content
        if: ${{ failure() }}
        run: |
          git diff --color=always
          exit 1

  golangci-lint-mcpservers:
    name: Lint MCP Servers
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "mcp-servers/go.mod"

      - name: Go test
        working-directory: mcp-servers
        run: |
          go test -v -timeout 30s -count=1 ./...

      - name: Run Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          working-directory: mcp-servers
          args: "--out-format colored-line-number --max-issues-per-linter 0 --max-same-issues 0 --config ./.golangci.yml"

      - name: Run Fix Linter
        uses: golangci/golangci-lint-action@v6
        if: ${{ failure() }}
        with:
          install-mode: none
          working-directory: mcp-servers
          args: "--fix --out-format colored-line-number --max-issues-per-linter 0 --max-same-issues 0 --config ./.golangci.yml"

      - name: Auto Fix Diff Content
        if: ${{ failure() }}
        run: |
          git diff --color=always
          exit 1

  golangci-lint-openapimcp:
    name: Lint OpneAPI MCP
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "openapi-mcp/go.mod"

      - name: Run Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          working-directory: openapi-mcp
          args: "--out-format colored-line-number --max-issues-per-linter 0 --max-same-issues 0 --config ./.golangci.yml"

      - name: Run Fix Linter
        uses: golangci/golangci-lint-action@v6
        if: ${{ failure() }}
        with:
          install-mode: none
          working-directory: openapi-mcp
          args: "--fix --out-format colored-line-number --max-issues-per-linter 0 --max-same-issues 0 --config ./.golangci.yml"

      - name: Auto Fix Diff Content
        if: ${{ failure() }}
        run: |
          git diff --color=always
          exit 1
